Repository AY2223S2-CS2103T-T14-1/tp, pull requests merged in 2023-03, with the labels that each got.

#68 Update AboutUs.md and create johnchiahk.md
  docs/AboutUs.md
  docs/images/johnchiahk.png
  docs/team/johnchiahk.md
  docs/team/johndoe.md
Labels: documentation

#70 Update user guide
  docs/UserGuide.md
Labels: documentation

#71 Update Site Wide Settings
  docs/_config.yml
  docs/_sass/minima/_base.scss
Labels: documentation

#72 Finalise v1.1 user guide
  docs/UserGuide.md
Labels: documentation

#65 Add Project, Deadline, Title, Status classes + tests
  src/main/java/arb/model/project/Deadline.java
  src/main/java/arb/model/project/Project.java
  src/main/java/arb/model/project/Status.java
  src/main/java/arb/model/project/Title.java
  src/test/java/arb/model/project/DeadlineTest.java
  src/test/java/arb/model/project/ProjectTest.java
  src/test/java/arb/model/project/StatusTest.java
  src/test/java/arb/model/project/TitleTest.java
  src/test/java/arb/testutil/ProjectBuilder.java
Labels: enhancement

#81 Update CLISyntax class to use agreed upon prefixes
  src/main/java/arb/logic/parser/CliSyntax.java
Labels: refactor

#75 Project Panel UI and Project List
  src/main/java/arb/logic/Logic.java
  src/main/java/arb/logic/LogicManager.java
  src/main/java/arb/logic/commands/Command.java
  src/main/java/arb/logic/commands/CommandResult.java
  src/main/java/arb/logic/commands/ExitCommand.java
  src/main/java/arb/logic/commands/HelpCommand.java
  src/main/java/arb/logic/commands/client/AddClientCommand.java
  src/main/java/arb/logic/commands/client/ClearClientCommand.java
  src/main/java/arb/logic/commands/client/DeleteClientCommand.java
  src/main/java/arb/logic/commands/client/EditClientCommand.java
  src/main/java/arb/logic/commands/client/FindClientCommand.java
  src/main/java/arb/logic/commands/client/ListClientCommand.java
  src/main/java/arb/model/AddressBook.java
  src/main/java/arb/model/ListType.java
  src/main/java/arb/model/Model.java
  src/main/java/arb/model/ModelManager.java
  src/main/java/arb/model/ReadOnlyAddressBook.java
  src/main/java/arb/model/project/Project.java
  src/main/java/arb/model/project/Status.java
  src/main/java/arb/model/project/UniqueProjectList.java
  src/main/java/arb/model/project/exceptions/DuplicateProjectException.java
  src/main/java/arb/model/project/exceptions/ProjectNotFoundException.java
  src/main/java/arb/ui/ClientCard.java
  src/main/java/arb/ui/MainWindow.java
  src/main/java/arb/ui/ProjectCard.java
  src/main/java/arb/ui/ProjectListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ProjectListCard.fxml
  src/main/resources/view/ProjectListPanel.fxml
  src/test/java/arb/logic/commands/CommandResultTest.java
  src/test/java/arb/logic/commands/CommandTestUtil.java
  src/test/java/arb/logic/commands/ExitCommandTest.java
  src/test/java/arb/logic/commands/HelpCommandTest.java
  src/test/java/arb/logic/commands/client/AddClientCommandIntegrationTest.java
  src/test/java/arb/logic/commands/client/AddClientCommandTest.java
  src/test/java/arb/logic/commands/client/ClearClientCommandTest.java
  src/test/java/arb/logic/commands/client/DeleteClientCommandTest.java
  src/test/java/arb/logic/commands/client/EditClientCommandTest.java
  src/test/java/arb/logic/commands/client/FindClientCommandTest.java
  src/test/java/arb/logic/commands/client/ListClientCommandTest.java
  src/test/java/arb/model/AddressBookTest.java
  src/test/java/arb/model/project/ProjectTest.java
  src/test/java/arb/model/project/UniqueProjectListTest.java
  src/test/java/arb/storage/JsonAddressBookStorageTest.java
  src/test/java/arb/storage/StorageManagerTest.java
  src/test/java/arb/testutil/ProjectBuilder.java
  src/test/java/arb/testutil/TypicalAddressBook.java
  src/test/java/arb/testutil/TypicalProjects.java
Labels: enhancement, enhancement.ui

#83 Implement add project feature
  src/main/java/arb/logic/commands/project/AddProjectCommand.java
  src/main/java/arb/logic/parser/AddressBookParser.java
  src/main/java/arb/logic/parser/ParserUtil.java
  src/main/java/arb/logic/parser/project/AddProjectCommandParser.java
  src/test/java/arb/logic/commands/CommandTestUtil.java
  src/test/java/arb/logic/commands/project/AddProjectCommandIntegrationTest.java
  src/test/java/arb/logic/commands/project/AddProjectCommandTest.java
  src/test/java/arb/logic/parser/project/AddProjectCommandParserTest.java
Labels: enhancement

#80 Make phone and email fields optional for Person
  src/main/java/arb/logic/parser/client/AddClientCommandParser.java
  src/main/java/arb/model/client/Client.java
  src/main/java/arb/storage/JsonAdaptedClient.java
  src/main/java/arb/ui/ClientCard.java
  src/main/resources/view/ClientListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalClientsAddressBook.json
  src/test/java/arb/model/client/ClientTest.java
  src/test/java/arb/storage/JsonAdaptedClientTest.java
  src/test/java/arb/testutil/ClientBuilder.java
  src/test/java/arb/testutil/TypicalClients.java
Labels: refactor

#82 Implement add client feature
  src/main/java/arb/logic/commands/client/AddClientCommand.java
  src/main/java/arb/logic/parser/client/AddClientCommandParser.java
  src/test/java/arb/logic/commands/client/AddClientCommandIntegrationTest.java
  src/test/java/arb/logic/commands/client/AddClientCommandTest.java
  src/test/java/arb/logic/parser/client/AddClientCommandParserTest.java
Labels: enhancement

#90 Implement Edit Client and Edit Command features
  src/main/java/arb/commons/core/Messages.java
  src/main/java/arb/logic/commands/client/EditClientCommand.java
  src/main/java/arb/logic/commands/project/EditProjectCommand.java
  src/main/java/arb/logic/parser/project/EditProjectCommandParser.java
Labels: enhancement

#87 Add deadline validation
  README.md
  build.gradle
  src/main/java/arb/model/client/Client.java
  src/main/java/arb/model/project/Deadline.java
  src/main/java/arb/model/project/Project.java
  src/main/java/arb/ui/ProjectCard.java
  src/test/java/arb/logic/commands/CommandTestUtil.java
  src/test/java/arb/logic/parser/project/AddProjectCommandParserTest.java
  src/test/java/arb/model/project/DeadlineTest.java
  src/test/java/arb/model/project/ProjectTest.java
  src/test/java/arb/testutil/ProjectBuilder.java
  src/test/java/arb/testutil/TypicalProjects.java
Labels: bug, testing

#101 Add messages to throw for duplicate client/project when editing clien…
  src/main/java/arb/commons/core/Messages.java
  src/main/java/arb/logic/commands/client/EditClientCommand.java
  src/main/java/arb/logic/commands/project/EditProjectCommand.java
  src/test/java/arb/logic/commands/client/EditClientCommandTest.java
Labels: enhancement

#97 Implement clear client command
  src/main/java/arb/logic/commands/client/ClearClientCommand.java
  src/main/java/arb/logic/commands/project/MarkProjectCommand.java
  src/main/java/arb/model/AddressBook.java
  src/main/java/arb/model/Model.java
  src/main/java/arb/model/ModelManager.java
  src/main/java/arb/model/project/Project.java
  src/main/java/arb/model/project/UniqueProjectList.java
  src/test/java/arb/logic/commands/client/AddClientCommandTest.java
  src/test/java/arb/logic/commands/client/ClearClientCommandTest.java
  src/test/java/arb/logic/commands/project/AddProjectCommandTest.java
Labels: enhancement

#108 Mark project command test
  src/test/java/arb/logic/commands/project/MarkProjectCommandTest.java
Labels: testing

#105 Implement find client and list client
  src/main/java/arb/logic/commands/client/FindClientCommand.java
  src/main/java/arb/logic/commands/client/ListClientCommand.java
  src/test/java/arb/logic/commands/client/ListClientCommandTest.java
Labels: enhancement

#100 Implement sort for client and project list
  src/main/java/arb/commons/core/sorting/ProjectSortingOption.java
  src/main/java/arb/logic/Logic.java
  src/main/java/arb/logic/LogicManager.java
  src/main/java/arb/logic/commands/client/DeleteClientCommand.java
  src/main/java/arb/logic/commands/client/EditClientCommand.java
  src/main/java/arb/logic/commands/client/ListClientCommand.java
  src/main/java/arb/logic/commands/client/SortClientCommand.java
  src/main/java/arb/logic/commands/project/EditProjectCommand.java
  src/main/java/arb/logic/commands/project/MarkProjectCommand.java
  src/main/java/arb/logic/commands/project/SortProjectCommand.java
  src/main/java/arb/logic/parser/AddressBookParser.java
  src/main/java/arb/logic/parser/CliSyntax.java
  src/main/java/arb/logic/parser/ParserUtil.java
  src/main/java/arb/logic/parser/project/SortProjectCommandParser.java
  src/main/java/arb/model/Model.java
  src/main/java/arb/model/ModelManager.java
  src/main/java/arb/model/client/Name.java
  src/main/java/arb/model/project/Deadline.java
  src/main/java/arb/model/project/Title.java
  src/main/java/arb/ui/MainWindow.java
  src/test/java/arb/commons/core/sorting/ProjectSortingOptionTest.java
  src/test/java/arb/logic/LogicManagerTest.java
  src/test/java/arb/logic/commands/CommandTestUtil.java
  src/test/java/arb/logic/commands/client/AddClientCommandTest.java
  src/test/java/arb/logic/commands/client/SortClientCommandTest.java
  src/test/java/arb/logic/commands/project/AddProjectCommandTest.java
  src/test/java/arb/logic/commands/project/SortProjectCommandTest.java
  src/test/java/arb/logic/parser/AddressBookParserTest.java
  src/test/java/arb/logic/parser/ParserUtilTest.java
  src/test/java/arb/logic/parser/project/SortProjectCommandParserTest.java
  src/test/java/arb/model/ModelManagerTest.java
  src/test/java/arb/testutil/AddressBookBuilder.java
  src/test/java/arb/testutil/TypicalProjectSortingOptions.java
Labels: enhancement

#102 Implement delete-client command
  src/main/java/arb/logic/commands/client/DeleteClientCommand.java
  src/test/java/arb/logic/LogicManagerTest.java
Labels: enhancement

#107 Implement list project and find project feature
  src/main/java/arb/commons/core/Messages.java
  src/main/java/arb/logic/commands/client/DeleteClientCommand.java
  src/main/java/arb/logic/commands/project/DeleteProjectCommand.java
  src/main/java/arb/logic/commands/project/EditProjectCommand.java
  src/main/java/arb/logic/commands/project/FindProjectCommand.java
  src/main/java/arb/logic/commands/project/ListProjectCommand.java
  src/main/java/arb/logic/parser/AddressBookParser.java
  src/main/java/arb/logic/parser/project/FindProjectCommandParser.java
  src/main/java/arb/logic/parser/project/UnmarkProjectCommandParser.java
  src/main/java/arb/model/project/TitleContainsKeywordsPredicate.java
  src/test/java/arb/logic/commands/CommandTestUtil.java
  src/test/java/arb/logic/commands/client/DeleteClientCommandTest.java
  src/test/java/arb/logic/commands/client/EditClientCommandTest.java
  src/test/java/arb/logic/commands/project/DeleteProjectCommandTest.java
  src/test/java/arb/logic/commands/project/EditProjectCommandTest.java
  src/test/java/arb/logic/commands/project/FindProjectCommandTest.java
  src/test/java/arb/logic/commands/project/ListProjectCommandTest.java
  src/test/java/arb/logic/commands/project/MarkProjectCommandTest.java
  src/test/java/arb/logic/commands/project/UnmarkProjectCommandTest.java
  src/test/java/arb/logic/parser/AddressBookParserTest.java
  src/test/java/arb/logic/parser/ParserUtilTest.java
  src/test/java/arb/logic/parser/project/EditProjectCommandParserTest.java
  src/test/java/arb/logic/parser/project/FindProjectCommandParserTest.java
  src/test/java/arb/logic/parser/project/MarkProjectCommandParserTest.java
  src/test/java/arb/logic/parser/project/UnmarkProjectCommandParserTest.java
  src/test/java/arb/model/project/ProjectTest.java
  src/test/java/arb/model/project/TitleContainsKeywordsPredicateTest.java
  src/test/java/arb/testutil/EditProjectDescriptorBuilder.java
  src/test/java/arb/testutil/ProjectUtil.java
Labels: enhancement

#113 Enable assertions
  build.gradle
Labels: refactor

#111 Mark project command test v1.2
  src/test/java/arb/model/project/ProjectTest.java
Labels: testing

#124 Implement aliases
  src/main/java/arb/commons/core/sorting/ProjectSortingOption.java
  src/main/java/arb/logic/commands/ExitCommand.java
  src/main/java/arb/logic/commands/HelpCommand.java
  src/main/java/arb/logic/commands/client/AddClientCommand.java
  src/main/java/arb/logic/commands/client/ClearClientCommand.java
  src/main/java/arb/logic/commands/client/DeleteClientCommand.java
  src/main/java/arb/logic/commands/client/EditClientCommand.java
  src/main/java/arb/logic/commands/client/FindClientCommand.java
  src/main/java/arb/logic/commands/client/ListClientCommand.java
  src/main/java/arb/logic/commands/client/SortClientCommand.java
  src/main/java/arb/logic/commands/project/AddProjectCommand.java
  src/main/java/arb/logic/commands/project/ClearProjectCommand.java
  src/main/java/arb/logic/commands/project/DeleteProjectCommand.java
  src/main/java/arb/logic/commands/project/EditProjectCommand.java
  src/main/java/arb/logic/commands/project/FindProjectCommand.java
  src/main/java/arb/logic/commands/project/ListProjectCommand.java
  src/main/java/arb/logic/commands/project/MarkProjectCommand.java
  src/main/java/arb/logic/commands/project/SortProjectCommand.java
  src/main/java/arb/logic/commands/project/UnmarkProjectCommand.java
  src/main/java/arb/logic/parser/AddressBookParser.java
  src/main/java/arb/logic/parser/ArgumentMultimap.java
  src/main/java/arb/logic/parser/ArgumentTokenizer.java
  src/main/java/arb/logic/parser/CliSyntax.java
  src/main/java/arb/logic/parser/Prefix.java
  src/main/java/arb/model/client/Client.java
  src/main/java/arb/model/project/Project.java
  src/test/java/arb/commons/core/sorting/ProjectSortingOptionTest.java
  src/test/java/arb/logic/LogicManagerTest.java
  src/test/java/arb/logic/commands/CommandTestUtil.java
  src/test/java/arb/logic/commands/client/AddClientCommandTest.java
  src/test/java/arb/logic/parser/AddressBookParserTest.java
  src/test/java/arb/logic/parser/ArgumentTokenizerTest.java
  src/test/java/arb/logic/parser/client/AddClientCommandParserTest.java
  src/test/java/arb/logic/parser/client/EditClientCommandParserTest.java
  src/test/java/arb/logic/parser/project/AddProjectCommandParserTest.java
  src/test/java/arb/logic/parser/project/EditProjectCommandParserTest.java
  src/test/java/arb/logic/parser/project/SortProjectCommandParserTest.java
  src/test/java/arb/testutil/ClientUtil.java
  src/test/java/arb/testutil/ProjectUtil.java
  src/test/java/arb/testutil/TypicalProjectSortingOptions.java
Labels: enhancement

#138 Update implementation of overdue status
  src/main/java/arb/model/project/Status.java
  src/main/java/arb/ui/ProjectCard.java
Labels: enhancement

#131 Ui overhaul
  src/main/java/arb/ui/MainWindow.java
  src/main/resources/view/ClientListPanel.fxml
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ProjectListPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: enhancement.ui

#132 Create money
  src/main/java/arb/logic/commands/project/AddProjectCommand.java
  src/main/java/arb/logic/commands/project/EditProjectCommand.java
  src/main/java/arb/logic/parser/CliSyntax.java
  src/main/java/arb/logic/parser/ParserUtil.java
  src/main/java/arb/logic/parser/project/AddProjectCommandParser.java
  src/main/java/arb/logic/parser/project/EditProjectCommandParser.java
  src/main/java/arb/model/project/Price.java
  src/main/java/arb/model/project/Project.java
  src/main/java/arb/model/project/UniqueProjectList.java
  src/main/java/arb/storage/JsonAdaptedProject.java
  src/main/java/arb/ui/ProjectCard.java
  src/main/resources/view/ProjectListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalProjectsAddressBook.json
  src/test/java/arb/storage/JsonAdaptedProjectTest.java
  src/test/java/arb/testutil/EditProjectDescriptorBuilder.java
  src/test/java/arb/testutil/ProjectBuilder.java
  src/test/java/arb/testutil/ProjectUtil.java
  src/test/java/arb/testutil/TypicalProjects.java
Labels: enhancement

#139 Dg john
  docs/DeveloperGuide.md
Labels: documentation

#140 Update DG with Project information
  docs/DeveloperGuide.md
Labels: documentation, priority.Medium

#133 Implement filtering for tags and timeframes
  src/main/java/arb/commons/core/predicate/CombinedPredicate.java
  src/main/java/arb/logic/commands/client/FindClientCommand.java
  src/main/java/arb/logic/commands/project/FindProjectCommand.java
  src/main/java/arb/logic/parser/CliSyntax.java
  src/main/java/arb/logic/parser/client/FindClientCommandParser.java
  src/main/java/arb/logic/parser/project/FindProjectCommandParser.java
  src/main/java/arb/model/ModelManager.java
  src/main/java/arb/model/client/ClientContainsTagPredicate.java
  src/main/java/arb/model/client/NameContainsKeywordsPredicate.java
  src/main/java/arb/model/project/ProjectContainsTagsPredicate.java
  src/main/java/arb/model/project/ProjectWithinTimeframePredicate.java
  src/main/java/arb/model/project/TitleContainsKeywordsPredicate.java
  src/main/java/arb/model/tag/TagMapping.java
  src/main/java/arb/model/tag/UniqueTagMappingList.java
  src/main/java/arb/ui/MainWindow.java
  src/test/java/arb/commons/predicate/CombinedPredicateTest.java
  src/test/java/arb/logic/parser/AddressBookParserTest.java
  src/test/java/arb/logic/parser/client/FindClientCommandParserTest.java
  src/test/java/arb/logic/parser/project/FindProjectCommandParserTest.java
  src/test/java/arb/model/client/ClientContainsTagPredicateTest.java
  src/test/java/arb/model/client/NameContainsKeywordsPredicateTest.java
  src/test/java/arb/model/project/ProjectContainsTagsPredicateTest.java
  src/test/java/arb/model/project/ProjectWithinTimeframePredicateTest.java
  src/test/java/arb/model/project/TitleContainsKeywordsPredicateTest.java
  src/test/java/arb/testutil/ClientUtil.java
  src/test/java/arb/testutil/PredicateUtil.java
  src/test/java/arb/testutil/ProjectUtil.java
Labels: enhancement

#148 Remove assert false
  src/main/java/arb/ui/MainWindow.java
Labels: bug

#153 Update Ui image in UG
  docs/UserGuide.md
  docs/images/Ui.png
Labels: documentation

#155 Update ug
  docs/UserGuide.md
Labels: documentation

#150 Implement ability to edit optional fields to be nullable (e.g. deadline/ makes deadline null)
  src/main/java/arb/logic/commands/client/EditClientCommand.java
  src/main/java/arb/logic/commands/project/EditProjectCommand.java
  src/main/java/arb/logic/parser/ParserUtil.java
  src/main/java/arb/logic/parser/project/EditProjectCommandParser.java
  src/test/java/arb/logic/parser/AddressBookParserTest.java
  src/test/java/arb/testutil/ClientUtil.java
  src/test/java/arb/testutil/ProjectUtil.java
Labels: enhancement

#163 User guide v2.0
  docs/UserGuide.md
Labels: documentation

#152 Allow added projects to be linked to clients
  src/main/java/arb/logic/Logic.java
  src/main/java/arb/logic/LogicManager.java
  src/main/java/arb/logic/commands/CommandResult.java
  src/main/java/arb/logic/commands/ExitCommand.java
  src/main/java/arb/logic/commands/HelpCommand.java
  src/main/java/arb/logic/commands/client/EditClientCommand.java
  src/main/java/arb/logic/commands/project/AddProjectCommand.java
  src/main/java/arb/logic/commands/project/EditProjectCommand.java
  src/main/java/arb/logic/commands/project/LinkProjectToClientCommand.java
  src/main/java/arb/logic/commands/project/MarkProjectCommand.java
  src/main/java/arb/logic/commands/project/UnmarkProjectCommand.java
  src/main/java/arb/logic/parser/CliSyntax.java
  src/main/java/arb/logic/parser/project/AddProjectCommandParser.java
  src/main/java/arb/logic/parser/project/EditProjectCommandParser.java
  src/main/java/arb/logic/parser/project/LinkProjectToClientCommandParser.java
  src/main/java/arb/model/AddressBook.java
  src/main/java/arb/model/Model.java
  src/main/java/arb/model/ModelManager.java
  src/main/java/arb/model/client/Client.java
  src/main/java/arb/model/client/UniqueClientList.java
  src/main/java/arb/model/project/Deadline.java
  src/main/java/arb/model/project/Project.java
  src/main/java/arb/model/project/UniqueProjectList.java
  src/main/java/arb/storage/JsonAdaptedProject.java
  src/main/java/arb/storage/JsonSerializableAddressBook.java
  src/main/java/arb/ui/MainWindow.java
  src/main/java/arb/ui/client/ClientCard.java
  src/main/java/arb/ui/project/ProjectCard.java
  src/main/resources/view/client/ClientListCard.fxml
  src/main/resources/view/project/ProjectListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalClientsAndProjectsAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalProjectsAddressBook.json
  src/test/java/arb/logic/commands/CommandResultTest.java
  src/test/java/arb/logic/commands/ExitCommandTest.java
  src/test/java/arb/logic/commands/HelpCommandTest.java
  src/test/java/arb/logic/commands/client/AddClientCommandTest.java
  src/test/java/arb/logic/commands/project/AddProjectCommandIntegrationTest.java
  src/test/java/arb/logic/commands/project/AddProjectCommandTest.java
  src/test/java/arb/logic/parser/AddressBookParserTest.java
  src/test/java/arb/logic/parser/project/AddProjectCommandParserTest.java
  src/test/java/arb/model/AddressBookTest.java
  src/test/java/arb/model/client/UniqueClientListTest.java
  src/test/java/arb/storage/JsonAdaptedProjectTest.java
  src/test/java/arb/testutil/ClientUtil.java
  src/test/java/arb/testutil/ProjectUtil.java
Labels: enhancement

#167 Change user guide link
  src/main/java/arb/ui/HelpWindow.java
Labels: bug

#168 Update tests
  src/main/java/arb/logic/commands/project/EditProjectCommand.java
  src/main/java/arb/logic/parser/project/AddProjectCommandParser.java
  src/main/java/arb/model/AddressBook.java
  src/main/java/arb/model/client/UniqueClientList.java
  src/main/java/arb/model/project/Project.java
  src/main/java/arb/model/project/UniqueProjectList.java
  src/test/java/arb/logic/commands/CommandResultTest.java
  src/test/java/arb/logic/commands/CommandTestUtil.java
  src/test/java/arb/logic/commands/ExitCommandTest.java
  src/test/java/arb/logic/commands/HelpCommandTest.java
  src/test/java/arb/logic/commands/project/AddProjectCommandIntegrationTest.java
  src/test/java/arb/logic/parser/ParserUtilTest.java
  src/test/java/arb/logic/parser/client/AddClientCommandParserTest.java
  src/test/java/arb/logic/parser/client/EditClientCommandParserTest.java
  src/test/java/arb/logic/parser/project/AddProjectCommandParserTest.java
  src/test/java/arb/logic/parser/project/EditProjectCommandParserTest.java
  src/test/java/arb/logic/parser/project/FindProjectCommandParserTest.java
  src/test/java/arb/logic/parser/project/LinkProjectToClientCommandParserTest.java
  src/test/java/arb/model/client/ClientTest.java
  src/test/java/arb/model/client/UniqueClientListTest.java
  src/test/java/arb/model/project/ProjectTest.java
  src/test/java/arb/model/project/UniqueProjectListTest.java
  src/test/java/arb/model/project/predicates/LinkedClientNameContainsKeywordsPredicateTest.java
  src/test/java/arb/storage/JsonAdaptedProjectTest.java
  src/test/java/arb/testutil/ClientBuilder.java
  src/test/java/arb/testutil/EditClientDescriptorBuilder.java
  src/test/java/arb/testutil/EditProjectDescriptorBuilder.java
  src/test/java/arb/testutil/ProjectBuilder.java
  src/test/java/arb/testutil/ProjectUtil.java
Labels: testing

#169 Implement filtering Projects by Status
  src/main/java/arb/logic/commands/project/FindProjectCommand.java
  src/main/java/arb/logic/parser/CliSyntax.java
  src/main/java/arb/logic/parser/ParserUtil.java
  src/main/java/arb/logic/parser/project/FindProjectCommandParser.java
  src/main/java/arb/model/project/Status.java
  src/main/java/arb/model/project/predicates/IsOfStatusPredicate.java
  src/main/java/arb/model/project/predicates/ProjectContainsTagsPredicate.java
  src/test/java/arb/logic/parser/ParserUtilTest.java
  src/test/java/arb/logic/parser/project/FindProjectCommandParserTest.java
  src/test/java/arb/model/project/predicates/IsOfStatusPredicateTest.java
Labels: enhancement

#173 Update commands in UG
  docs/UserGuide.md
Labels: documentation

#171 Update OVERDUE display in Ui
  src/main/java/arb/ui/project/ProjectCard.java
  src/main/resources/view/project/ProjectListCard.fxml
Labels: enhancement.ui

#172 Info on project list
  src/main/java/arb/logic/commands/project/ListProjectCommand.java
  src/main/java/arb/model/AddressBook.java
  src/main/java/arb/model/Model.java
  src/main/java/arb/model/ModelManager.java
  src/main/java/arb/model/project/Project.java
  src/main/java/arb/model/project/Status.java
  src/main/java/arb/model/project/UniqueProjectList.java
  src/test/java/arb/logic/commands/client/AddClientCommandTest.java
  src/test/java/arb/logic/commands/project/AddProjectCommandTest.java
  src/test/java/arb/logic/commands/project/ListProjectCommandTest.java
  src/test/java/arb/model/project/PriceTest.java
Labels: enhancement.ui

#174 Update UG
  docs/UserGuide.md
  src/main/java/arb/model/UserPrefs.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/arb/logic/LogicManagerTest.java
  src/test/java/arb/storage/JsonUserPrefsStorageTest.java
Labels: documentation

#175 Update command summary table
  docs/UserGuide.md
Labels: documentation

#185 Add startup message
  src/main/java/arb/MainApp.java
  src/main/java/arb/storage/JsonStorageState.java
  src/main/java/arb/ui/MainWindow.java
  src/main/java/arb/ui/UiManager.java
Labels: enhancement.ui

#186 List parameters used for find commands
  src/main/java/arb/commons/core/predicate/CombinedPredicate.java
  src/main/java/arb/logic/commands/client/FindClientCommand.java
  src/main/java/arb/logic/commands/project/FindProjectCommand.java
  src/main/java/arb/model/client/predicates/ClientContainsTagPredicate.java
  src/main/java/arb/model/client/predicates/NameContainsKeywordsPredicate.java
  src/main/java/arb/model/project/predicates/IsOfStatusPredicate.java
  src/main/java/arb/model/project/predicates/LinkedClientNameContainsKeywordsPredicate.java
  src/main/java/arb/model/project/predicates/ProjectContainsTagsPredicate.java
  src/main/java/arb/model/project/predicates/ProjectWithinTimeframePredicate.java
  src/main/java/arb/model/project/predicates/TitleContainsKeywordsPredicate.java
  src/test/java/arb/logic/commands/client/FindClientCommandTest.java
  src/test/java/arb/logic/commands/project/FindProjectCommandTest.java
Labels: enhancement.ui

#187 Allow cancelling for linking
  src/main/java/arb/commons/core/index/Index.java
  src/main/java/arb/commons/util/StringUtil.java
  src/main/java/arb/logic/commands/project/LinkProjectToClientCommand.java
  src/main/java/arb/logic/parser/ParserUtil.java
  src/main/java/arb/logic/parser/client/DeleteClientCommandParser.java
  src/main/java/arb/logic/parser/project/DeleteProjectCommandParser.java
  src/main/java/arb/logic/parser/project/LinkProjectToClientCommandParser.java
  src/main/java/arb/logic/parser/project/MarkProjectCommandParser.java
  src/main/java/arb/logic/parser/project/UnmarkProjectCommandParser.java
  src/main/java/arb/model/AddressBook.java
  src/main/java/arb/model/Model.java
  src/main/java/arb/model/ModelManager.java
  src/test/java/arb/logic/commands/client/AddClientCommandTest.java
  src/test/java/arb/logic/commands/project/AddProjectCommandTest.java
Labels: enhancement

#188 Fix space between tags
  src/main/java/arb/model/tag/Tag.java
Labels: enhancement.ui

#189 Reset client list when adding project fails due to not found client
  src/main/java/arb/logic/commands/project/AddProjectCommand.java
  src/main/java/arb/logic/commands/project/EditProjectCommand.java
Labels: bug, enhancement.ui

#194 Concatenate name, tag, client keywords for find command and link commands
  src/main/java/arb/logic/commands/project/AddProjectCommand.java
  src/main/java/arb/logic/commands/project/EditProjectCommand.java
  src/main/java/arb/logic/parser/client/AddClientCommandParser.java
  src/main/java/arb/logic/parser/client/FindClientCommandParser.java
  src/main/java/arb/logic/parser/project/AddProjectCommandParser.java
  src/main/java/arb/logic/parser/project/EditProjectCommandParser.java
  src/main/java/arb/logic/parser/project/FindProjectCommandParser.java
  src/main/java/arb/logic/parser/project/LinkProjectToClientCommandParser.java
  src/test/java/arb/logic/commands/project/AddProjectCommandIntegrationTest.java
  src/test/java/arb/logic/commands/project/AddProjectCommandTest.java
  src/test/java/arb/logic/parser/AddressBookParserTest.java
  src/test/java/arb/logic/parser/project/AddProjectCommandParserTest.java
  src/test/java/arb/logic/parser/project/EditProjectCommandParserTest.java
  src/test/java/arb/logic/parser/project/FindProjectCommandParserTest.java
  src/test/java/arb/logic/parser/project/LinkProjectToClientCommandParserTest.java
  src/test/java/arb/testutil/EditProjectDescriptorBuilder.java
  src/test/java/arb/testutil/ProjectUtil.java
Labels: bug, enhancement

#196 Fix bug: status does not carry over when editing project
  src/main/java/arb/logic/commands/project/EditProjectCommand.java
  src/main/java/arb/model/project/Project.java
Labels: bug

#195 Fix bug: made JSON tag parsing case-insensitive
  src/main/java/arb/storage/JsonAdaptedTag.java
Labels: bug

#198 Make command words insensitive
  src/main/java/arb/MainApp.java
  src/main/java/arb/logic/parser/AddressBookParser.java
  src/test/java/arb/testutil/TypicalClients.java
Labels: enhancement

#200 Throw exception only when there are a mix of empty and non-empty client prefixes
  src/main/java/arb/MainApp.java
  src/main/java/arb/logic/parser/project/EditProjectCommandParser.java
Labels: enhancement
