Repository AY2223S2-CS2103T-T14-1/tp, pull requests merged in 2023-04, with the labels that each got.

#245 Fix bug: end date of find-project can be before start date
  src/main/java/arb/logic/commands/project/FindProjectCommand.java
  src/main/java/arb/logic/parser/project/FindProjectCommandParser.java
Labels: bug-fix

#246 Update UG
  docs/UserGuide.md
Labels: documentation

#247 Update PPP draft
  docs/team/zrei.md
Labels: documentation

#250 Update ug sections
  docs/UserGuide.md
  docs/images/DataFileLocation.png
  docs/images/LinkSuccessful.png
  docs/images/LinkingCancelled.png
  docs/images/LinkingExample.png
  docs/images/Ui.png
  docs/images/UiAnnotated.png
  docs/images/helpMessage.png
Labels: documentation

#251 Update index
  docs/UserGuide.md
  docs/index.md
Labels: documentation

#252 Update PPP
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/johnchiahk.md
  docs/team/verydaftpunk.md
Labels: documentation

#253 DG: Update Architecture Section
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ClientClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ProjectClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/TagMappingClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/ClientClassDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ProjectClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/TagMappingClassDiagram.png
  docs/images/UiClassDiagram.png
  src/main/java/arb/logic/LogicManager.java
  src/main/java/arb/logic/parser/AddressBookParser.java
  src/test/java/arb/logic/parser/AddressBookParserTest.java
Labels: documentation

#254 Update user guide command format and summary
  docs/UserGuide.md
Labels: documentation

#248 Update list project content
  src/main/java/arb/logic/commands/project/ListProjectCommand.java
  src/main/java/arb/model/AddressBook.java
  src/main/java/arb/model/Model.java
  src/main/java/arb/model/ModelManager.java
  src/main/java/arb/model/project/UniqueProjectList.java
  src/test/java/arb/logic/commands/client/AddClientCommandTest.java
  src/test/java/arb/logic/commands/project/AddProjectCommandTest.java
  src/test/java/arb/logic/commands/project/ListProjectCommandTest.java
Labels: enhancement

#255 Update mmaimer33's PPP
  docs/team/mmaimer33.md
Labels: documentation

#256 Update dg
  README.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/SortingSequenceDiagram.puml
  docs/images/SortingSequenceDiagram.png
  docs/index.md
  docs/team/mmaimer33.md
  docs/team/zrei.md
Labels: documentation

#257 Update DG user stories and testing
  docs/DeveloperGuide.md
  docs/index.md
Labels: documentation

#260 Update testing instructions
  docs/DeveloperGuide.md
Labels: documentation

#261 Update user stories
  docs/DeveloperGuide.md
  docs/diagrams/ClientClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
Labels: documentation

#265 Update linking implementation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ClientClassDiagram.puml
  docs/diagrams/ExampleLinkedObjectDiagram.puml
  docs/diagrams/LinkedClassDiagram.puml
  docs/diagrams/LinkingAlternateClassDiagram.puml
  docs/diagrams/LinkingIndexParsingSequenceDiagram.puml
  docs/diagrams/LinkingParsingSequenceDiagram.puml
  docs/diagrams/style.puml
  docs/images/ExampleLinkedObjectDiagram.png
  docs/images/LinkedClassDiagram.png
  docs/images/LinkingAlternateClassDiagram.png
  docs/images/LinkingIndexParsingSequenceDiagram.png
  docs/images/LinkingParsingSequenceDiagram.png
Labels: documentation

#267 Update filtering section
  docs/DeveloperGuide.md
  docs/diagrams/CombinedPredicateClassDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/FindUpdateFilteredClientListSequenceDiagram.puml
  docs/diagrams/LinkingParsingSequenceDiagram.puml
  docs/diagrams/style.puml
  docs/images/CombinedPredicateClassDiagram.png
  docs/images/FindSequenceDiagram.png
  docs/images/FindUpdateFilteredClientListSequenceDiagram.png
  docs/images/LinkingParsingSequenceDiagram.png
Labels: documentation

#268 Update model diagram
  docs/DeveloperGuide.md
  docs/diagrams/ModelAndAddressBookClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelAndAddressBookClassDiagram.png
  docs/images/ModelClassDiagram.png
Labels: documentation

#269 Update feature flaws
  docs/DeveloperGuide.md
  docs/diagrams/FindUpdateFilteredClientListSequenceDiagram.puml
  docs/images/FindUpdateFilteredClientListSequenceDiagram.png
Labels: documentation

#270 Update diagram size
  docs/DeveloperGuide.md
Labels: documentation

#275 Update diagrams
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddressBookClientDiagram.puml
  docs/diagrams/AddressBookProjectDiagram.puml
  docs/diagrams/AddressBookTagMappingDiagram.puml
  docs/diagrams/CombinedPredicateClassDiagram.puml
  docs/diagrams/LinkedClassDiagram.puml
  docs/images/AddressBookClientDiagram.png
  docs/images/AddressBookProjectDiagram.png
  docs/images/AddressBookTagMappingDiagram.png
  docs/images/CombinedPredicateClassDiagram.png
  docs/images/LinkedClassDiagram.png
Labels: documentation

#276 Adjust diagram sizes
  docs/DeveloperGuide.md
  docs/diagrams/LinkedClassDiagram.puml
  docs/images/LinkedClassDiagram.png
Labels: documentation

#277 Do final refactors
  docs/diagrams/LinkingAlternateClassDiagram.puml
  docs/images/LinkingAlternateClassDiagram.png
  src/main/java/arb/MainApp.java
  src/main/java/arb/commons/core/Messages.java
  src/main/java/arb/logic/parser/client/FindClientCommandParser.java
  src/main/java/arb/logic/parser/project/FindProjectCommandParser.java
  src/main/java/arb/model/AddressBook.java
  src/main/java/arb/model/client/predicates/ClientContainsTagsPredicate.java
  src/main/java/arb/model/project/Project.java
  src/main/java/arb/model/project/predicates/ProjectWithinTimeframePredicate.java
Labels: documentation, refactor

#278 Update UG
  docs/UserGuide.md
  docs/images/ClientList.png
  docs/images/SortClient1.png
  docs/images/SortClient2.png
  docs/images/SortClient3.png
  src/main/java/arb/logic/commands/client/SortClientCommand.java
Labels: documentation

#282 Update UG project command details
  docs/UserGuide.md
  docs/images/SortProject1.png
  docs/images/SortProject2.png
  docs/images/SortProject3.png
Labels: documentation

#281 Update UG formatting
  docs/UserGuide.md
Labels: documentation

#283 Add invisible space
  docs/UserGuide.md
  docs/_config.yml
Labels: documentation

#284 Align paragraphs
  docs/UserGuide.md
Labels: documentation

#285 Update README
  README.md
Labels: documentation

#286 Add additional images
  docs/UserGuide.md
  docs/images/ListProjectExample.png
  docs/images/ListTagExample.png
Labels: documentation

#287 Update casing
  docs/UserGuide.md
Labels: documentation

#290 Move details
  docs/UserGuide.md
Labels: documentation

#292 Update product name
  README.md
  docs/Documentation.md
  docs/SettingUp.md
  docs/Testing.md
  docs/UserGuide.md
  docs/_config.yml
  docs/_sass/minima/_base.scss
  docs/index.md
  docs/team/zrei.md
Labels: documentation

#293 Update NFRs and appendix for effort in DG
  docs/DeveloperGuide.md
Labels: documentation

#294 Update links
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/index.md
Labels: documentation

#296 Update command table
  docs/UserGuide.md
Labels: documentation

#297 Update command messages to match UG
  docs/UserGuide.md
  src/main/java/arb/logic/commands/client/AddClientCommand.java
  src/main/java/arb/logic/commands/client/DeleteClientCommand.java
  src/main/java/arb/logic/commands/client/EditClientCommand.java
  src/main/java/arb/logic/commands/client/FindClientCommand.java
  src/main/java/arb/logic/commands/project/AddProjectCommand.java
  src/main/java/arb/logic/commands/project/DeleteProjectCommand.java
  src/main/java/arb/logic/commands/project/EditProjectCommand.java
  src/main/java/arb/logic/commands/project/FindProjectCommand.java
  src/main/java/arb/logic/commands/project/MarkProjectCommand.java
  src/main/java/arb/logic/commands/project/SortProjectCommand.java
  src/main/java/arb/logic/commands/project/UnmarkProjectCommand.java
Labels: documentation, improve err msg

#299 Add delete command details to DG
  docs/DeveloperGuide.md
  docs/diagrams/DeleteClientSequenceDiagram.puml
  docs/diagrams/DeleteProjectSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/DeleteClientSequenceDiagram.png
  docs/images/DeleteProjectSequenceDiagram.png
  docs/images/UiClassDiagram.png
Labels: documentation

#301 Update UG FAQs
  docs/UserGuide.md
Labels: documentation

#302 Update UG
  README.md
  docs/UserGuide.md
  docs/diagrams/DeleteClientSequenceDiagram.puml
  docs/diagrams/DeleteProjectSequenceDiagram.puml
  docs/index.md
  docs/team/johnchiahk.md
  docs/team/zrei.md
Labels: documentation

#303 Update dg
  docs/DeveloperGuide.md
  docs/team/zrei.md
Labels: documentation

#305 Update mmaimer33's PPP
  docs/team/mmaimer33.md
Labels: documentation

#306 Add page breaks to UG
  docs/UserGuide.md
Labels: documentation

#307 Fix broken link on AboutUs
  docs/AboutUs.md
Labels: documentation

#308 Update documentation final
  docs/UserGuide.md
Labels: documentation

#309 Shift page breaks
  docs/UserGuide.md
Labels: documentation

#310 Add page break
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#311 Shift page breaks
  docs/UserGuide.md
Labels: documentation

#312 Add page breaks
  docs/UserGuide.md
Labels: documentation

#313 Update user stories and glossary
  docs/DeveloperGuide.md
Labels: documentation

#315 Update use cases formatting
  docs/DeveloperGuide.md
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
Labels: documentation

#316 Add line breaks to dg
  docs/DeveloperGuide.md
  docs/diagrams/FindSequenceDiagram.puml
  docs/images/FindSequenceDiagram.png
Labels: documentation

#317 Add line breaks
  docs/DeveloperGuide.md
Labels: documentation

#319 Add line break
  docs/DeveloperGuide.md
Labels: documentation

#320 Add line breaks
  docs/DeveloperGuide.md
Labels: documentation

#321 Add line break
  docs/DeveloperGuide.md
Labels: documentation

#322 Add line break
  docs/DeveloperGuide.md
Labels: documentation

#324 Add line break
  docs/DeveloperGuide.md
Labels: documentation

#325 Add line break
  docs/DeveloperGuide.md
Labels: documentation

#326 Add skeleton of remaining use cases
  docs/DeveloperGuide.md
  src/main/java/arb/MainApp.java
Labels: documentation

#334 Update use cases
  docs/DeveloperGuide.md
Labels: documentation

#335 Add line break
  docs/DeveloperGuide.md
Labels: documentation

#336 Add line break
  docs/DeveloperGuide.md
Labels: documentation

#337 Add line break
  docs/DeveloperGuide.md
Labels: documentation

#338 Add line break
  docs/DeveloperGuide.md
Labels: documentation

#339 Add line break
  docs/DeveloperGuide.md
Labels: documentation
